name: apm-agent-ios
options:
  minimumXcodeGenVersion: 2.10.1
  deploymentTarget:
    iOS: "13.0"
    tvOS: "13.0"
    macOS: "10.15"
packages:
  opentelemetry-swift:
    url: https://github.com/open-telemetry/opentelemetry-swift
    exactVersion: 1.9.1
  reachability:
    url: https://github.com/ashleymills/Reachability.swift
    from: 5.2.2
  kronos:
    url: https://github.com/MobileNativeFoundation/Kronos.git
    from: 4.2.2
  PLCrashReporter:
    url: https://github.com/microsoft/plcrashreporter.git
    from: 1.0.0
targets:
  ElasticApm:
    type: framework
    platform: [iOS, macOS, tvOS]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "co.elastic.ElasticApm"
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGNING_ALLOWED: NO
    sources:
      - Sources/apm-agent-ios
      - path: Sources/apm-agent-ios/Resources/ElasticApm.h
        buildPhase: headers
        headerVisibility: public
    dependencies:
      - package: reachability
        products:
          - Reachability
      - package: kronos
        products:
          - Kronos
      - package: PLCrashReporter
        product: CrashReporter
      - package: opentelemetry-swift
        products:
          - OpenTelemetryApi
          - OpenTelemetrySdk
          - OpenTelemetryProtocolExporter
          - PersistenceExporter
          - URLSessionInstrumentation
          - ResourceExtension
