#!/usr/bin/env groovy

@Library('apm@current') _

pipeline {
  agent { label 'macosx-10.15' }
  environment {
    REPO = 'apm-agent-ios'
    BASE_DIR = "src/github.com/elastic/${env.REPO}"
    NOTIFY_TO = credentials('notify-to')
  }
  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20', daysToKeepStr: '30'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    rateLimitBuilds(throttle: [count: 60, durationName: 'hour', userBoost: true])
    quietPeriod(10)
  }
  triggers {
    issueCommentTrigger('(?i)(.*(?:jenkins\\W+)?run\\W+(?:the\\W+)?tests(?:\\W+please)?.*|^/test(?:\\W+.*)?$)')
  }
  stages {
    stage('Initializing'){
      options { skipDefaultCheckout() }
      stages{
        stage('Checkout') {
          options { skipDefaultCheckout() }
          steps {
            pipelineManager([ cancelPreviousRunningBuilds: [ when: 'PR' ] ])
            deleteDir()
            gitCheckout(basedir: "${BASE_DIR}", githubNotifyFirstTimeContributor: true)
            stash allowEmpty: true, name: 'source', useDefaultExcludes: false
          }
        }
        stage('Build') {
          steps {
            withGithubNotify(context: 'Build') {
              deleteDir()
              unstash 'source'
              dir("${BASE_DIR}"){
                sh 'xcodebuild -scheme iOSAgent'
              }
            }
          }
        }
        stage('Test') {
          steps {
            withGithubNotify(context: 'Test') {
              deleteDir()
              unstash 'source'
              dir("${BASE_DIR}"){
                sh "xcodebuild -scheme apm-agent-iosTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' test"
              }
            }
          }
        }
      }
    }
  }
  post {
    cleanup {
      deleteDir()
      notifyBuildResult()
    }
  }
}
