[[best-practices]]
== Best Practices
Care must be taken when deploying iOS to products: Once an app is released, it becomes very difficult to ensure device owners update to newer versions; therefore making changes to APM server's endpoint or authenticate can result in these older versions having no way to report their data.

=== Allow anonymous connections to your APM server.

Enable 'Anonymous agent access' through the apm integration setting, and ensure `iOS/swift` is added to the list of "Allowed agents". Depending on your expected app usage, you may need to adjust the rate limits under the same settings. More details on anonymous authentication can be found in at https://www.elastic.co/guide/en/apm/guide/current/configuration-anonymous.html[configure
anonymous authentication].

=== Assign a domain to your APM server.
Assigning a domain to your APM server will give your deployment more flexibility. The underlying server or IP this domain points to can change, but as long as the domain name stays the same, data from deployed agents can still be received.