[[configuration]]
== Configuration

Configure the agent with `AgentConfigBuilder` passing the `AgentConfiguration` to the `start` function.

// some config example that preferably is correct unlike mine
[source,swift]
----
let config = AgentConfigBuilder()
                .withServerUrl(URL(string: "http://localhost:8200"))
                .withSecretToken("<Token>")
                .build()

Agent.start(with:config)
----

The `AgentConfigBuilder` can be configured with the following functions

[discrete]
[[configuration-options]]
=== Configuration options

[discrete]
[[withServerUrl]]
==== `withServerUrl`

* *Type:* URL
* *Default:* `http://127.0.0.1:8200`

[discrete]
[[secretToken]]
==== `withSecretToken`
* *Type:* String
* *Default:* nil
* *Env:* `OTEL_EXPORTER_OTLP_HEADERS`

Sets the secret token for connecting to an authenticated APM Server. If using the env-var, the whole header map must be defined per https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md[OpenTelemetry Protocol Exporter Config] (e.g.: `OTEL_EXPORTER_OTLP_HEADERS="Authorization=bearer <secret token>"`)

This setting is mutually exclusive with `withApiKey`

[discrete]
[[withApiKey]]
==== `withApiKey`
* *Type:* String
* *Default:* nil
* *Env:* `OTEL_EXPORTER_OTLP_HEADERS`

Sets the API Token for connecting to an authenticated APM Server. If using the env-var, the whole header map must be defined per https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md[OpenTelemetry Protocol Exporter Config] (e.g.: `OTEL_EXPORTER_OTLP_HEADERS="Authorization=ApiKey <key>"`)

This setting is mutually exclusive with `withSecretToken`

[discrete]
[[disableAgent]]
===== `disableAgent() -> Self`
Disables the Elastic agent. This is useful for disabling the agent during development without having to remove the Elastic agent completely. A log will report `"Elastic APM Agent has been disabled."`

[discrete]
[[addSpanFilter]]
==== `addSpanFilter`
* *Type:* @escaping (ReadableSpan) -> Bool
* *Default:* nil

Adds an anonymous function that will be executed on each span in the span processor to decide if that span should be sent to the back end.


[discrete]
[[addMetricFilter]]
==== `addMetricFilter`
* *Type:* @escaping (Metric) -> Bool
* *Default:* nil


Adds an anonymous function that will be executed on each metric in the span processor to decide if that metric should be sent to the back end.

[discrete]
[[addLogFilter]]
==== `addLogFilter
* *Type:* @escaping (ReadableLogRecord) -> Bool
* *Default:* nil

Adds an anonymous function that will be executed on each log in the span processor to decide if that log should be sent to the back end.

[discrete]
[[resourceAttributeInjection]]
== Resource attribute injection
In v0.5.0, the agent provides a means to set https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#specifying-resource-information-via-an-environment-variable[resource attributes] using the `OTEL_RESOURCE_ATTRIBUTES` env-var. This env-var also works through the application plist. Any resource attribute  can be overridden using this method, so care should be taken, as some attributes are critical to the functioning of the kibana UI.

[discrete]
[[deplyoment-environment]]
=== `deployment.environment`
Deployment environment is set to `default`. This can be overridden using the `OTEL_RESOURCE_ATTRIBUTES` set in your deployment's plist. Use the field key as `OTEL_RESOURCE_ATTRIBUTES` and the value as `deployment.environment=staging`

[discrete]
[[dynamic-configuration]]
=== Dynamic configuration image:./images/dynamic-config.svg[]

Dynamic configurations are available through the kibana UI and are read by the agent remotely to apply configuration on all active agents deployed in the field. More info on dynamic configurations can be found in  {kibana-ref}/agent-configuration.html[agent configurations].

[discrete]
[[recording]]
==== Recording
A boolean specifying if the agent should be recording or not. When recording, the agent instruments incoming HTTP requests, tracks errors and collects and sends metrics. When not recording, the agent works as a noop, not collecting data and not communicating with the APM sever, except for polling the central configuration endpoint. As this is a reversible switch, agent threads are not being killed when inactivated, but they will be mostly idle in this state, so the overhead should be negligible.

You can set this setting to dynamically disable Elastic APM at runtime

image:./images/dynamic-config.svg[]

[options="header"]
|============
| Default                          | Type                | Dynamic
| `true` | Boolean | true
|============

[discrete]
[[session-sample-rate]]
==== Session sample rate
A double specifying the likelihood all data generated during a session should be recorded on a specific device. Value may range between 0 and 1. 1 meaning 100% likely, and 0 meaning 0% likely. Everytime a new session starts, this value will be checked against a random number between 0 and 1, and will sample all data recorded in that session of the random number is below the session sample rate set.

This session focused sampling technique is to preserve related data points, as opposed to sampling signal by signal, where valuable context can be lost.

You can set this value dynamically at runtime.

image:./images/dynamic-config.svg[]

[options="header"]
|============
| Default                          | Type                | Dynamic
| `1.0` | Double  | true
|============
