[[intro]]
== Introduction

The Elastic APM iOS Agent measures the performance of your mobile applications in real-time.

[float]
[[how-it-works]]
=== How does the agent work?
The Elastic APM iOS Agent uses the https://github.com/open-telemetry/opentelemetry-swift[OpenTelemetry-Swift SDK].
The agent automatically traces URLSessions and provides distributed traces annotated with device information along
with your back-end services instrumented with Open-Telemetry.

The agent also captures any custom open-telemetry traces or measurements created using the OpenTelemetry-Swift API.

[float]
[[manual-instrumentation]]
=== How to add instrumentation
This agent will configure the OpenTelementry-Swift `TracerProvider` and `MetricProvider`, and set them as the global OpenTelemetry providers. They can be accessed through the OpenTelemetry SDK as follows:

[source,swift]
----
let tracerProvider = OpenTelemetry.instance.tracerProvider
let meterProvider = OpenTelemetry.instance.meterProvider
----

These objects can be used to acquire new tracers and meters that will send their captured data to the Elastic APM Server. More details on how to use OpenTelemetry to instrument your app can be found in the https://opentelemetry.io/docs/instrumentation/swift/manual[OpenTelemetry.io Swift manual instrumentation docs].

Examples can be found in https://github.com/open-telemetry/opentelemetry-swift/tree/main/Examples[opentelemetry-swift/examples].

[discrete]
[[additional-components]]
=== Additional components
APM Agents work in conjunction with the {apm-guide-ref}/index.html[APM Server], {ref}/index.html[{es}], and {kibana-ref}/index.html[{kib}].
The {apm-guide-ref}/index.html[APM Guide] provides details on how these components work together,
and provides a matrix outlining {apm-guide-ref}/agent-server-compatibility.html[Agent and Server compatibility].

[discrete]
=== Open Telemetry Components
The iOS Agent utilizes several OpenTelemetry-Swift libraries to provide automatic instrumentation of your applications and services. Details about these instrumentation libraries can be found in the official https://opentelemetry.io/docs/instrumentation/swift/libraries/[opentelementry.io Swift Libraries documentation].

For network instrumentation, the agent uses `NSURLSessionInstrumentation`. This provides network instrumentation in the form of spans and enables distributed tracing for all instrumented downstream services.

Detailed information on the device, operating system, and application is provided by `SDKResourceExtension`. More information on which data points are captured can be found in the  https://opentelemetry.io/docs/instrumentation/swift/manual/#SDKResourceExtension[opentelementry.io SDKResourceExtension documentation].

Elastic maps OpenTelemetry attributes to Elastic-specific fields. Details of these mappings can be found in the https://github.com/elastic/apm/tree/main/specs/agents/mobile[Elastic Mobile Agent Spec].