[[intro]]
== Introduction

The Elastic APM iOS Agent measures the performance of your mobile applications in real-time.

[float]
[[how-it-works]]
=== How does the Agent work?
The Elastic APM iOS Agent uses the https://github.com/open-telemetry/opentelemetry-swift[OpenTelemetry-Swift SDK].
The Agent will automatically trace URLSessions and provide distributed traces annotated with device information along
with your back-end services instrumented with Open-Telemetry.
This Agent will also capture any custom open-telemetry traces or measurements captured using the OpenTelemetry-Swift API.

[discrete]
[[additional-components]]
=== Additional components
APM Agents work in conjunction with the {apm-server-ref-v}/index.html[APM Server], {ref}/index.html[{es}], and {kibana-ref}/index.html[{kib}].
The {apm-overview-ref-v}/index.html[APM Overview] provides details on how these components work together,
and provides a matrix outlining {apm-overview-ref-v}/agent-server-compatibility.html[Agent and Server compatibility].
