[[setup]]
== Set up the Agent

:source-highlighter: coderay

[discrete]
[[requirements]]
=== Requirements

This project requires Swift `5.7`, and is intended for use in Swift-base mobile apps.

Other platform requires:

[options="header"]
|===
| platform | version
| `iOS` | `11`
|`macOS` | `10.13`
| `tvOS` | `v11`
| `watchOS` | `3`
|===


[discrete]
[[add-agent-dependency]]
=== Add the Agent dependency
Add the Elastic APM iOS Agent to your Xcode project or your `Package.swift`.

Here are instructions for adding a https://developer.apple.com/documentation/swift_packages/adding_package_dependencies_to_your_app[package dependency] to a standard Xcode poject.

Details of adding dependencies to your Package.swift can be found on https://developer.apple.com/documentation/xcode/creating_a_standalone_swift_package_with_xcode#3578941['Add a Dependency on Another Swift Package'].
Below is a helpful code-snippet:

`package.swift`:
[source,swift,linenums,highlight=2;10]
----
Package(
    dependencies:[
         .package(name: "apm-agent-ios", url: "https://github.com/elastic/apm-agent-ios.git", from: "0.8.0"),
    ],
  targets:[
    .target(
        name: "MyApp",
        dependencies: [
            .product(name: "iOSAgent", package: "apm-agent-ios")
        ]
    ),
])
----

[discrete]
[[initialize]]
=== Initialize the agent
Once the Agent has been added as a dependency, it must be initialized.

If you're using `SwiftUI` to build your app add the following to your `App.swift`:

[source,swift,linenums,swift,highlight=2;4..15;19]
----
import SwiftUI
import iOSAgent

class AppDelegate : NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        var config = AgentConfigBuilder()
            .withServerUrl(URL(string:"http://127.0.0.1:8200")) <1>
            .withSecretToken("<SecretToken>") <2>
            .build()
        
        Agent.start(with: config)
        return true
    }
}

@main
struct MyApp: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    init() {
    }
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
----
<1> APM Server URL
<2> Set secret token for APM server connection

If you're not using `SwiftUI` you can alternatively add the same thing to your AppDelegate file:

`AppDelegate.swift`
[source,swift,linenums,highlight=2;7..11]
----
import UIKit
import iOSAgent
@main
class AppDelegate: UIResponder, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
var config = AgentConfigBuilder()
                       .withServerUrl(URL(string:"http://127.0.0.1:8200")) <1>
                       .withSecretToken("<SecretToken>") <2>
                       .build()
        Agent.start(with: config)
        return true
    }
}
----
<1> APM Server URL
<2> Set secret token for APM server connection



