name: Create Release PR
on: 
  workflow_dispatch:
    inputs:
      new_version:
        description: "New sdk version"
        required: true
jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with: 
        ref: ${{ github.head_ref }}
    - name: validate package dependencies
      run: |
        RESULT=$(swift package show-dependencies | grep unspecified)
        if [ -n "$RESULT" ]; then
          echo "Unspecified dependencies found in the package:"
          echo "$RESULT"
          exit 1
        else
          echo "All dependencies are specified correctly."
        fi
    - name: update version file
      run: |
        sed -e 's/<NEW_VERSION>/${{ inputs.new_version }}/' Version.template > Sources/apm-agent-ios/Version.swift

    - name: update docs versions
      run: | 
        sed -i -e 's/from: ".*"),$/from: "${inputs.new_version}"),/' docs/reference/set-up-apm-ios-agent.md
        OPENTELEMETRY_VERSION=$(sed -E -n 's/[[:space:]]+url: "https:\/\/github.com\/open-telemetry\/opentelemetry-swift", exact: "(.*)"\),$/\1/p' Package.swift)
        sed -i -e 's/| OpenTelemetry-Swift | .* |/| OpenTelemetry-Swift | ${OPENTELEMETRY_VERSION} |/' docs/reference/supported-technologies.md 
    - name: Get token
      id: get_token
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
      with:
        app_id: ${{ secrets.RELEASE_TOKEN }}
        private_key: ${{ secrets.RELEASE_TOKEN_PEM }}
        permissions: >-
          {
            "contents": "write",
            "pull_requests": "write"
          }
        repositories: >-
          ["apm-agent-ios"]
    - name: Setup github CLI
      uses: elastic/oblt-actions/git/setup@v1
    - name: Create pull request 
      run: |
        git checkout -b release/${{inputs.new_version}}
        git add .
        git commit -m "Release ${inputs.new_version}"
        gh pr create -- title "Release ${{inputs.new_version}}" --body "This PR is auto-generated by create-pull-request." --base main --head release/${{inputs.new_version}} --delete-branch
        