name: macos

on:
  push:
    tags:
      - v*.*.*
    branches:
      - main

permissions:
  contents: read

jobs:
  cocoapods:
    runs-on: macos-12
    permissions:
      attestations: write
      contents: write
      id-token: write
    # If no PR event or if a PR event that's caused by a non-fork and non dependabot actor
    if: github.event_name != 'pull_request' || ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]' )
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run build
        run: .ci/scripts/build.sh

      - name: Run package snapshots
        run: .ci/scripts/package.sh

      - name: Generate build provenance
        uses: actions/attest-build-provenance@173725a1209d09b31f9d30a3890cf2757ebbff0d  # v1.1.2
        with:
          subject-path: "${{ github.workspace }}/dist/*"

      - name: Create github release (only for tag release)
        if: startsWith(github.ref, 'refs/tags')
        run: |
          readonly LATEST_GIT_TAG=$(git tag --list --sort=version:refname "v*" | grep -v - | tail -n1)
          if [[ "$GITHUB_REF_NAME" == "$LATEST_GIT_TAG" ]]; then
            IS_LATEST=true
          else
            IS_LATEST=false
          fi
          echo "INFO: Create '$GITHUB_REF_NAME' GitHub release (latest=$IS_LATEST)."
          gh release create "$GITHUB_REF_NAME" \
            --title "$GITHUB_REF_NAME" \
            --latest=$IS_LATEST \
            ./dist/*
        env:
          GH_TOKEN: ${{ github.token }}
