---

name: snapshoty
on:
  workflow_run:
    workflows:
      - macos
    types:
      - completed

permissions:
  contents: read

jobs:
  macos-publish-snapshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: snapshoty
    - name: Publish snaphosts
      uses: elastic/apm-pipeline-library/.github/actions/snapshoty-simple@current
      with:
        config: '.ci/snapshoty.yml'
        vaultUrl: ${{ secrets.VAULT_ADDR }}
        vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
        vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
